Delete project usecase implementation
wojiaotreaty/CSC207_Project pull request #19
Opened 2023-11-26 19:08 UTC by bing-j

Code associated with #5. Note that no tests have been written yet.
@skrtsamjang @BraedenChoo

2023-11-27 19:04 UTC, skrtsamjang reviewed
I think it's all good, I was wondering at first how you would handle if there were no projects to delete, but I guess you are handling the deletion inside the projectview and not the dashboard view, then which you won't need a fail case of deleting projects. You might have to check with Vedant to see if the layout of the project view is matching your use case.

2023-11-27 21:44 UTC, BraedenChoo reviewed
Nice work, but there are a few formatting and syntax errors I've pointed out you should resolve first.

2023-11-27 21:44 UTC, BraedenChoo commented on src/use_case/delete_project/DeleteProjectDataAccessInterface.java
> +    User getCurrentUser();
I'm sure you know but just so you remember, this method is deprecated.

2023-11-27 21:44 UTC, BraedenChoo commented on src/use_case/delete_project/DeleteProjectInteractor.java
> +        User currentUser = userDataAccessObject.getCurrentUser();
just a reminder to refactor this for getUser(String)

2023-11-30 17:56 UTC, skrtsamjang requested changes
I think it's pretty good, just some minor convention mistakes as well as some redundant methods, but other than that great job.

2023-11-30 19:49 UTC, BraedenChoo approved these changes
Looks good now!

2023-11-30 19:52 UTC, skrtsamjang approved these changes
i believe it works now

2023-11-30 19:53 UTC, merged