Login, Login View Implementation, Signup, Signup View Implementation Pull Request
wojiaotreaty/CSC207_Project pull request #22
Opened 2023-11-27 01:44 UTC by skrtsamjang

**Overview:**

This pull request introduces 4 issues: Login, Login View Implementation, Signup and Signup View Implementation. 

First, the Login feature allows the user to access the account that is specific to the user, given that their username and passwords match. When the Login is successful, the login interactor will pass user information to the dashboard view (#16 ).

Changes Made to Login use case:

1.  **LoginInteractor.java:** 
      - When the user inputs username and password, checks to see if the user exists, and if the password matches the username.
      - Upon successful login,  the interactor will access the User Object as well as its corresponding Project and Task entities and organize the information into an ArrayList<ArrayList<String>> data which is created  into an output data and passed on to the login presenter

2. **LoginInputData.java:**
      - Implemented attributes from week5ca LoginInputData file

3. **LoginOutputData.java:**
      - Implemented attributes from week5ca LoginOutputData file with the addition of the ArrayList<ArrayList<String>> as the project data.
      - getter method for the project data

4. **login directory**
      - created all three files under the login directory which is under the use_case directory.
      - Other than the files above, there exists the LoginDataAccessInterface.java, LoginInputBoundary.java, and LoginOutputBoundary.java

Changes made to Login View:

1. **LoginController.java:**
      - Implemented attributes from week5ca LoginController file

2. **LoginPresenter.java**
      - Implemented attributes from week5ca LoginPresenter file
      - The presenter will proceed to dashboardViewModel instead of loggedinViewModel 
      - preparing a successful view switches the state and view model to dashboard specific view model, passing the project data that is in the form of ArrayList<ArrayList<String>>.

3. **LoginState.java:**
      - Implemented attributes from week5ca LoginState file

4. **LoginViewModel.java**
      - Implemented attributes from week5ca LoginViewModel file

5. **login directory (interface_adapter):**
      - Created a login directory with all four files above
      - Directory under interface_adapter directory

6. **LoginView.java**
      - Implemented attributes from week5ca LoginView file
      - Added a signup button when clicked, switches over to Signup View
      - Added actionListener to signup button, so that it passes it to signup controller to switch view to signup

**Changes made to Signup use case:**

1.  **SignupInteractor.java:** 
      - Implmented attributes from week5ca SignupInteractor file
      - Upon successful signup,  the interactor will create a new User Object, which will be one of the entities that Braeden implements

2. **SignupInputData.java:**
      - Implemented attributes from week5ca SignupInputData file

3. **SignupOutputData.java:**
      - Implemented attributes from week5ca SignupOutputData file 
      - Commented out the CreationTime attribute, as it is not necessary in the application

4. **signup directory**
      - created all three files under the signup directory which is under the use_case directory.
      - Other than the files above, there exists the SignupDataAccessInterface.java, SignupInputBoundary.java, and SignupOutputBoundary.java

Changes made to Signup View:

1. **SignupController.java:**
      - Implemented attributes from week5ca SignupController file

2. **SignupPresenter.java**
      - Implemented attributes from week5ca SignupPresenter file
      - Commented out the use for Creation for now, as it seems unnecessary

3. **SignupState.java:**
      - Implemented attributes from week5ca SignupState file

4. **SignupViewModel.java**
      - Implemented attributes from week5ca SignupViewModel file

5. **signup directory (interface_adapter):**
      - Created a signup directory with all four files above
      - Directory under interface_adapter directory

6. **SignupView.java**
      - Implemented attributes from week5ca SignupView file
      - Commented out Cancel button to remove unnecessary action listening

**Other changes/implementation outside of the four issues**

1. **ViewManagerModel.java:**
      - Implemented attributes from week5ca ViewManagerModel file so that it can manage which view model to set up

2. **app:**
      - Implemented LoginUseCaseFactory, SignupUseCaseFactory and Main file from week5ca coding
      - replaced the logged in view models and states with dashboard view models and states
      - changed Main so that instead of calling signup view, it calls login view first. This will is a mock Main for my own use, but not runnable unless merged with entities.

3. **dashboard:**
      - Created a dashboard directory under interface_adapter for temporary reference to DashboardState and DashboardViewModel. Will be replaced with William's Dashboard implementation

4. **data_access**
      - Created UsersDataAccessObject file which is for Bing's DAO implementation

5. **entity:**
      - Created files for User and UserFactory and their corresponding interfaces which were implemented from week5ca. Will be replaced with Braeden's entities for User, Project, and Task

6. **DashboardView.java:**
      - Placeholder view class for dashboard. Will be replaced with William's Dashboard View implementation.

**Reviewers:**
      - @wojiaotreaty 
      - @VedantTheGreat 
      - @BraedenChoo 
      - @bing-j 

**Associated Issues:**
      - #11 
      - #21 
      - #20 
      - #2

2023-11-27 03:24 UTC, bing-j requested changes
Thank you for your work! See comments that start with ISSUE and SUGGESTION for requested changes

2023-11-30 19:54 UTC, bing-j approved these changes
Looks good!

2023-11-30 20:58 UTC, BraedenChoo commented on src/use_case/login/LoginInteractor.java
> +                User user = userDataAccessObject.getUser(loginInputData.getUsername());
Not a big deal but loginInputData.getUsername() is already saved in the variable username, so there isn't a need to call this method again.

2023-11-30 20:58 UTC, BraedenChoo commented on src/use_case/login/LoginInteractor.java
> +                ArrayList<Project> listofproject = user.getProjects(); // get arraylist of projects
listofproject should probably be made listOfProject in order to follow camel case naming conventions.

2023-11-30 20:58 UTC, BraedenChoo commented on src/use_case/login/LoginInteractor.java
> +                    String stringTasks = "";
stringTasks can be made a StringBuilder, since it is more efficient to append to a StringBuilder than concatenate strings.

2023-11-30 20:58 UTC, BraedenChoo commented on src/use_case/signup/SignupOutputData.java
> +//    public String getCreationTime() {
What are these commented out methods for?

2023-11-30 20:58 UTC, BraedenChoo commented on src/view/SignupView.java
> +                    }
below here and in the passwordInputField as well as repeatPasswordInputField, there are these keyPressed methods that don't seem to do anything?

2023-11-30 20:58 UTC, BraedenChoo commented on src/view/LoginView.java
> +            }
There are these keyPressed methods that don't seem to do anything here, as well as in passwordInputField.

2023-11-30 22:45 UTC, merged