Entities creation
wojiaotreaty/CSC207_Project pull request #23
Opened 2023-11-27 02:51 UTC by BraedenChoo

Created entities User, Project, and Task:
User: Stores username, password, and an ArrayList of Projects. Implements addProject and deleteProject methods.
Project: Stores project id, project name, project description, and an ArrayList of Tasks associated with each Project. Implements addTask and removeTask methods.
Task: Stores task name, description, deadline, and status. Implements setStatus and toString method.

2023-11-27 04:47 UTC, bing-j approved these changes
Awesome! See comments that start with SUGGESTION for edits that I think should be made but don't impact the code functionality.

However, note that the already finished use cases use the interfaces User, Project, Task, as well as UserFactory and ProjectFactory. (I don't think a TaskFactory interface was used anywhere but I'm not sure. It could be useful to have though). So please update the entities to match with the interface methods that are requested by the use cases in future commits!

2023-11-27 04:47 UTC, bing-j commented on src/entity/Project.java
> +        return (ArrayList<Task>) tasks.clone();
Nice!

2023-11-27 04:47 UTC, bing-j commented on src/entity/Project.java
> +    public void addTask(Task task) {
Also nice!

2023-11-27 04:47 UTC, bing-j commented on src/entity/Task.java
> +    public String toString() {
SUGGESTION: needs a docstring describing the format of the task string

2023-11-27 04:47 UTC, bing-j commented on src/entity/User.java
> +    public Project deleteProject(String id) {
SUGGESTION: needs a docstring describing what is returned under which condition

2023-11-30 17:41 UTC, wojiaotreaty commented on src/entity/UwuProject.java
Looks good! Just a side note though, do we need to overload the constructor when all instantiations of UwuProject happen inside a Project factory? You can always control exactly how UwuProject is instantiated within the ProjectFactory.

2023-11-30 17:50 UTC, wojiaotreaty commented on src/entity/UwuProjectFactory.java
Using a factory for UwuProject brings up a good opportunity to implement the open/closed principle. Some food for thought for the future is that maybe we could overload UwuProjectFactory.create method to potentially take in a String projectType parameter in case we decide to have multiple types of projects. The current create method would create the default project if no projectType is provided. Just an idea!

2023-11-30 18:05 UTC, wojiaotreaty commented on src/entity/UwuTaskFactory.java
When UwuTaskFactory is called from the add project use case interaction, deadline is passed in as a string generated by the API. Please overload the create method to accept this as a possible parameter.

2023-11-30 18:21 UTC, wojiaotreaty requested changes
Great job on the code! Looks great overall. I left some comments, mostly suggestions, however, there is one change I'm requesting for ProjectFactory. Please see the comment made on that file.

2023-11-30 21:39 UTC, wojiaotreaty approved these changes
Approving this merge request...

2023-11-30 22:43 UTC, merged